// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyTurn.Infrastructure.Data;

#nullable disable

namespace MyTurn.Infrastructure.Data.Migrations
{
    [DbContext(typeof(MyTurnDbContext))]
    [Migration("20260707025009_WorldObjectsAndLayout")]
    partial class WorldObjectsAndLayout
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("MyTurn.Infrastructure.Data.Entities.EnemyActionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("EnemyDefinitionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("Weight")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EnemyDefinitionId");

                    b.ToTable("EnemyActions");
                });

            modelBuilder.Entity("MyTurn.Infrastructure.Data.Entities.EnemyDefinitionEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("ExperienceReward")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("ThreatRating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<string>("WeaponItemId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WeaponItemId");

                    b.ToTable("EnemyDefinitions");
                });

            modelBuilder.Entity("MyTurn.Infrastructure.Data.Entities.EnemyLootDropEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EnemyDefinitionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("MaxQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MinQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Weight")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EnemyDefinitionId");

                    b.ToTable("EnemyLootDrops");
                });

            modelBuilder.Entity("MyTurn.Infrastructure.Data.Entities.EnemySpawnWeightEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EnemyDefinitionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("Weight")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EnemyDefinitionId")
                        .IsUnique();

                    b.ToTable("EnemySpawnWeights");
                });

            modelBuilder.Entity("MyTurn.Infrastructure.Data.Entities.EnemyStatEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EnemyDefinitionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("StatType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EnemyDefinitionId", "StatType")
                        .IsUnique();

                    b.ToTable("EnemyStats");
                });

            modelBuilder.Entity("MyTurn.Infrastructure.Data.Entities.ItemDefinitionEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("EquipmentSlot")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int?>("HealingAmount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsStackable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int?>("MaxDamage")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MinDamage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("SuggestedLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<int>("Tier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<string>("WeaponType")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ItemDefinitions");
                });

            modelBuilder.Entity("MyTurn.Infrastructure.Data.Entities.ItemStatModifierEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemDefinitionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("StatType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ItemDefinitionId", "StatType", "Value");

                    b.ToTable("ItemStatModifiers");
                });

            modelBuilder.Entity("MyTurn.Infrastructure.Data.Entities.PartyInventoryStackEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SaveSlotId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("SaveSlotId", "ItemId")
                        .IsUnique();

                    b.ToTable("PartyInventoryStacks");
                });

            modelBuilder.Entity("MyTurn.Infrastructure.Data.Entities.PartyMemberEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ActiveOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CharacterClass")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SaveSlotId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("Steps")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SaveSlotId", "ActiveOrder")
                        .IsUnique();

                    b.ToTable("PartyMembers");
                });

            modelBuilder.Entity("MyTurn.Infrastructure.Data.Entities.PartyMemberEquipmentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PartyMemberId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Slot")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("PartyMemberId", "Slot")
                        .IsUnique();

                    b.ToTable("PartyMemberEquipment");
                });

            modelBuilder.Entity("MyTurn.Infrastructure.Data.Entities.PartyMemberSkillEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Experience")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PartyMemberId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SkillType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PartyMemberId", "SkillType")
                        .IsUnique();

                    b.ToTable("PartyMemberSkills");
                });

            modelBuilder.Entity("MyTurn.Infrastructure.Data.Entities.PartyMemberStatEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseValue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxValue")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PartyMemberId")
                        .HasColumnType("TEXT");

                    b.Property<string>("StatType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PartyMemberId", "StatType")
                        .IsUnique();

                    b.ToTable("PartyMemberStats");
                });

            modelBuilder.Entity("MyTurn.Infrastructure.Data.Entities.SaveSlotEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("Currency")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastPlayedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long>("Steps")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SaveSlots");
                });

            modelBuilder.Entity("MyTurn.Infrastructure.Data.Entities.WorldObjectEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EncounterSeed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBlocking")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ObjectType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorldSessionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("X")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Y")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WorldSessionId", "ObjectId")
                        .IsUnique();

                    b.HasIndex("WorldSessionId", "X", "Y");

                    b.ToTable("WorldObjects");
                });

            modelBuilder.Entity("MyTurn.Infrastructure.Data.Entities.WorldRoomEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EncounterSeed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCleared")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLooted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVisited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoomType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorldSessionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("X")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Y")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WorldSessionId", "X", "Y")
                        .IsUnique();

                    b.ToTable("WorldRooms");
                });

            modelBuilder.Entity("MyTurn.Infrastructure.Data.Entities.WorldSessionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentY")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LayoutId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("LayoutSource")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxCoordinate")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinCoordinate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProfileId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SaveSlotId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Seed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SaveSlotId", "IsCompleted");

                    b.ToTable("WorldSessions");
                });

            modelBuilder.Entity("MyTurn.Infrastructure.Data.Entities.EnemyActionEntity", b =>
                {
                    b.HasOne("MyTurn.Infrastructure.Data.Entities.EnemyDefinitionEntity", "EnemyDefinition")
                        .WithMany("Actions")
                        .HasForeignKey("EnemyDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnemyDefinition");
                });

            modelBuilder.Entity("MyTurn.Infrastructure.Data.Entities.EnemyDefinitionEntity", b =>
                {
                    b.HasOne("MyTurn.Infrastructure.Data.Entities.ItemDefinitionEntity", "WeaponItem")
                        .WithMany()
                        .HasForeignKey("WeaponItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("WeaponItem");
                });

            modelBuilder.Entity("MyTurn.Infrastructure.Data.Entities.EnemyLootDropEntity", b =>
                {
                    b.HasOne("MyTurn.Infrastructure.Data.Entities.EnemyDefinitionEntity", "EnemyDefinition")
                        .WithMany("LootDrops")
                        .HasForeignKey("EnemyDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnemyDefinition");
                });

            modelBuilder.Entity("MyTurn.Infrastructure.Data.Entities.EnemySpawnWeightEntity", b =>
                {
                    b.HasOne("MyTurn.Infrastructure.Data.Entities.EnemyDefinitionEntity", "EnemyDefinition")
                        .WithOne("SpawnWeight")
                        .HasForeignKey("MyTurn.Infrastructure.Data.Entities.EnemySpawnWeightEntity", "EnemyDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnemyDefinition");
                });

            modelBuilder.Entity("MyTurn.Infrastructure.Data.Entities.EnemyStatEntity", b =>
                {
                    b.HasOne("MyTurn.Infrastructure.Data.Entities.EnemyDefinitionEntity", "EnemyDefinition")
                        .WithMany("Stats")
                        .HasForeignKey("EnemyDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnemyDefinition");
                });

            modelBuilder.Entity("MyTurn.Infrastructure.Data.Entities.ItemStatModifierEntity", b =>
                {
                    b.HasOne("MyTurn.Infrastructure.Data.Entities.ItemDefinitionEntity", "ItemDefinition")
                        .WithMany("StatModifiers")
                        .HasForeignKey("ItemDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemDefinition");
                });

            modelBuilder.Entity("MyTurn.Infrastructure.Data.Entities.PartyInventoryStackEntity", b =>
                {
                    b.HasOne("MyTurn.Infrastructure.Data.Entities.ItemDefinitionEntity", "ItemDefinition")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyTurn.Infrastructure.Data.Entities.SaveSlotEntity", "SaveSlot")
                        .WithMany("InventoryStacks")
                        .HasForeignKey("SaveSlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemDefinition");

                    b.Navigation("SaveSlot");
                });

            modelBuilder.Entity("MyTurn.Infrastructure.Data.Entities.PartyMemberEntity", b =>
                {
                    b.HasOne("MyTurn.Infrastructure.Data.Entities.SaveSlotEntity", "SaveSlot")
                        .WithMany("PartyMembers")
                        .HasForeignKey("SaveSlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SaveSlot");
                });

            modelBuilder.Entity("MyTurn.Infrastructure.Data.Entities.PartyMemberEquipmentEntity", b =>
                {
                    b.HasOne("MyTurn.Infrastructure.Data.Entities.ItemDefinitionEntity", "ItemDefinition")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyTurn.Infrastructure.Data.Entities.PartyMemberEntity", "PartyMember")
                        .WithMany("Equipment")
                        .HasForeignKey("PartyMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemDefinition");

                    b.Navigation("PartyMember");
                });

            modelBuilder.Entity("MyTurn.Infrastructure.Data.Entities.PartyMemberSkillEntity", b =>
                {
                    b.HasOne("MyTurn.Infrastructure.Data.Entities.PartyMemberEntity", "PartyMember")
                        .WithMany("Skills")
                        .HasForeignKey("PartyMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PartyMember");
                });

            modelBuilder.Entity("MyTurn.Infrastructure.Data.Entities.PartyMemberStatEntity", b =>
                {
                    b.HasOne("MyTurn.Infrastructure.Data.Entities.PartyMemberEntity", "PartyMember")
                        .WithMany("Stats")
                        .HasForeignKey("PartyMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PartyMember");
                });

            modelBuilder.Entity("MyTurn.Infrastructure.Data.Entities.WorldObjectEntity", b =>
                {
                    b.HasOne("MyTurn.Infrastructure.Data.Entities.WorldSessionEntity", "WorldSession")
                        .WithMany("Objects")
                        .HasForeignKey("WorldSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorldSession");
                });

            modelBuilder.Entity("MyTurn.Infrastructure.Data.Entities.WorldRoomEntity", b =>
                {
                    b.HasOne("MyTurn.Infrastructure.Data.Entities.WorldSessionEntity", "WorldSession")
                        .WithMany("Rooms")
                        .HasForeignKey("WorldSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorldSession");
                });

            modelBuilder.Entity("MyTurn.Infrastructure.Data.Entities.WorldSessionEntity", b =>
                {
                    b.HasOne("MyTurn.Infrastructure.Data.Entities.SaveSlotEntity", "SaveSlot")
                        .WithMany("WorldSessions")
                        .HasForeignKey("SaveSlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SaveSlot");
                });

            modelBuilder.Entity("MyTurn.Infrastructure.Data.Entities.EnemyDefinitionEntity", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("LootDrops");

                    b.Navigation("SpawnWeight");

                    b.Navigation("Stats");
                });

            modelBuilder.Entity("MyTurn.Infrastructure.Data.Entities.ItemDefinitionEntity", b =>
                {
                    b.Navigation("StatModifiers");
                });

            modelBuilder.Entity("MyTurn.Infrastructure.Data.Entities.PartyMemberEntity", b =>
                {
                    b.Navigation("Equipment");

                    b.Navigation("Skills");

                    b.Navigation("Stats");
                });

            modelBuilder.Entity("MyTurn.Infrastructure.Data.Entities.SaveSlotEntity", b =>
                {
                    b.Navigation("InventoryStacks");

                    b.Navigation("PartyMembers");

                    b.Navigation("WorldSessions");
                });

            modelBuilder.Entity("MyTurn.Infrastructure.Data.Entities.WorldSessionEntity", b =>
                {
                    b.Navigation("Objects");

                    b.Navigation("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
