// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyTurn.Infrastructure.Data;

#nullable disable

namespace MyTurn.Infrastructure.Data.Migrations
{
    [DbContext(typeof(MyTurnDbContext))]
    partial class MyTurnDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("MyTurn.Infrastructure.Data.Entities.EnemyActionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("EnemyDefinitionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("Weight")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EnemyDefinitionId");

                    b.ToTable("EnemyActions");
                });

            modelBuilder.Entity("MyTurn.Infrastructure.Data.Entities.EnemyDefinitionEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("ExperienceReward")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("WeaponItemId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WeaponItemId");

                    b.ToTable("EnemyDefinitions");
                });

            modelBuilder.Entity("MyTurn.Infrastructure.Data.Entities.EnemyLootDropEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EnemyDefinitionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("MaxQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MinQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Weight")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EnemyDefinitionId");

                    b.ToTable("EnemyLootDrops");
                });

            modelBuilder.Entity("MyTurn.Infrastructure.Data.Entities.EnemySpawnWeightEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EnemyDefinitionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("Weight")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EnemyDefinitionId")
                        .IsUnique();

                    b.ToTable("EnemySpawnWeights");
                });

            modelBuilder.Entity("MyTurn.Infrastructure.Data.Entities.EnemyStatEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EnemyDefinitionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("StatType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EnemyDefinitionId", "StatType")
                        .IsUnique();

                    b.ToTable("EnemyStats");
                });

            modelBuilder.Entity("MyTurn.Infrastructure.Data.Entities.ItemDefinitionEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("EquipmentSlot")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int?>("HealingAmount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsStackable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int?>("MaxDamage")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MinDamage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("WeaponType")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ItemDefinitions");
                });

            modelBuilder.Entity("MyTurn.Infrastructure.Data.Entities.ItemStatModifierEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemDefinitionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("StatType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ItemDefinitionId", "StatType", "Value");

                    b.ToTable("ItemStatModifiers");
                });

            modelBuilder.Entity("MyTurn.Infrastructure.Data.Entities.PlayerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CharacterClass")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("Currency")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SaveSlotId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("Steps")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SaveSlotId")
                        .IsUnique();

                    b.ToTable("Players");
                });

            modelBuilder.Entity("MyTurn.Infrastructure.Data.Entities.PlayerEquipmentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Slot")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("PlayerId", "Slot")
                        .IsUnique();

                    b.ToTable("PlayerEquipment");
                });

            modelBuilder.Entity("MyTurn.Infrastructure.Data.Entities.PlayerInventoryStackEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("PlayerId", "ItemId")
                        .IsUnique();

                    b.ToTable("PlayerInventoryStacks");
                });

            modelBuilder.Entity("MyTurn.Infrastructure.Data.Entities.PlayerSkillEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Experience")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SkillType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "SkillType")
                        .IsUnique();

                    b.ToTable("PlayerSkills");
                });

            modelBuilder.Entity("MyTurn.Infrastructure.Data.Entities.PlayerStatEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseValue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxValue")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("StatType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "StatType")
                        .IsUnique();

                    b.ToTable("PlayerStats");
                });

            modelBuilder.Entity("MyTurn.Infrastructure.Data.Entities.SaveSlotEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastPlayedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SaveSlots");
                });

            modelBuilder.Entity("MyTurn.Infrastructure.Data.Entities.WorldRoomEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EncounterSeed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCleared")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLooted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVisited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoomType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorldSessionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("X")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Y")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WorldSessionId", "X", "Y")
                        .IsUnique();

                    b.ToTable("WorldRooms");
                });

            modelBuilder.Entity("MyTurn.Infrastructure.Data.Entities.WorldSessionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentY")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxCoordinate")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinCoordinate")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SaveSlotId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Seed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SaveSlotId", "IsCompleted");

                    b.ToTable("WorldSessions");
                });

            modelBuilder.Entity("MyTurn.Infrastructure.Data.Entities.EnemyActionEntity", b =>
                {
                    b.HasOne("MyTurn.Infrastructure.Data.Entities.EnemyDefinitionEntity", "EnemyDefinition")
                        .WithMany("Actions")
                        .HasForeignKey("EnemyDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnemyDefinition");
                });

            modelBuilder.Entity("MyTurn.Infrastructure.Data.Entities.EnemyDefinitionEntity", b =>
                {
                    b.HasOne("MyTurn.Infrastructure.Data.Entities.ItemDefinitionEntity", "WeaponItem")
                        .WithMany()
                        .HasForeignKey("WeaponItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("WeaponItem");
                });

            modelBuilder.Entity("MyTurn.Infrastructure.Data.Entities.EnemyLootDropEntity", b =>
                {
                    b.HasOne("MyTurn.Infrastructure.Data.Entities.EnemyDefinitionEntity", "EnemyDefinition")
                        .WithMany("LootDrops")
                        .HasForeignKey("EnemyDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnemyDefinition");
                });

            modelBuilder.Entity("MyTurn.Infrastructure.Data.Entities.EnemySpawnWeightEntity", b =>
                {
                    b.HasOne("MyTurn.Infrastructure.Data.Entities.EnemyDefinitionEntity", "EnemyDefinition")
                        .WithOne("SpawnWeight")
                        .HasForeignKey("MyTurn.Infrastructure.Data.Entities.EnemySpawnWeightEntity", "EnemyDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnemyDefinition");
                });

            modelBuilder.Entity("MyTurn.Infrastructure.Data.Entities.EnemyStatEntity", b =>
                {
                    b.HasOne("MyTurn.Infrastructure.Data.Entities.EnemyDefinitionEntity", "EnemyDefinition")
                        .WithMany("Stats")
                        .HasForeignKey("EnemyDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnemyDefinition");
                });

            modelBuilder.Entity("MyTurn.Infrastructure.Data.Entities.ItemStatModifierEntity", b =>
                {
                    b.HasOne("MyTurn.Infrastructure.Data.Entities.ItemDefinitionEntity", "ItemDefinition")
                        .WithMany("StatModifiers")
                        .HasForeignKey("ItemDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemDefinition");
                });

            modelBuilder.Entity("MyTurn.Infrastructure.Data.Entities.PlayerEntity", b =>
                {
                    b.HasOne("MyTurn.Infrastructure.Data.Entities.SaveSlotEntity", "SaveSlot")
                        .WithOne("Player")
                        .HasForeignKey("MyTurn.Infrastructure.Data.Entities.PlayerEntity", "SaveSlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SaveSlot");
                });

            modelBuilder.Entity("MyTurn.Infrastructure.Data.Entities.PlayerEquipmentEntity", b =>
                {
                    b.HasOne("MyTurn.Infrastructure.Data.Entities.ItemDefinitionEntity", "ItemDefinition")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyTurn.Infrastructure.Data.Entities.PlayerEntity", "Player")
                        .WithMany("Equipment")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemDefinition");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("MyTurn.Infrastructure.Data.Entities.PlayerInventoryStackEntity", b =>
                {
                    b.HasOne("MyTurn.Infrastructure.Data.Entities.ItemDefinitionEntity", "ItemDefinition")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyTurn.Infrastructure.Data.Entities.PlayerEntity", "Player")
                        .WithMany("InventoryStacks")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemDefinition");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("MyTurn.Infrastructure.Data.Entities.PlayerSkillEntity", b =>
                {
                    b.HasOne("MyTurn.Infrastructure.Data.Entities.PlayerEntity", "Player")
                        .WithMany("Skills")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("MyTurn.Infrastructure.Data.Entities.PlayerStatEntity", b =>
                {
                    b.HasOne("MyTurn.Infrastructure.Data.Entities.PlayerEntity", "Player")
                        .WithMany("Stats")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("MyTurn.Infrastructure.Data.Entities.WorldRoomEntity", b =>
                {
                    b.HasOne("MyTurn.Infrastructure.Data.Entities.WorldSessionEntity", "WorldSession")
                        .WithMany("Rooms")
                        .HasForeignKey("WorldSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorldSession");
                });

            modelBuilder.Entity("MyTurn.Infrastructure.Data.Entities.WorldSessionEntity", b =>
                {
                    b.HasOne("MyTurn.Infrastructure.Data.Entities.SaveSlotEntity", "SaveSlot")
                        .WithMany("WorldSessions")
                        .HasForeignKey("SaveSlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SaveSlot");
                });

            modelBuilder.Entity("MyTurn.Infrastructure.Data.Entities.EnemyDefinitionEntity", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("LootDrops");

                    b.Navigation("SpawnWeight");

                    b.Navigation("Stats");
                });

            modelBuilder.Entity("MyTurn.Infrastructure.Data.Entities.ItemDefinitionEntity", b =>
                {
                    b.Navigation("StatModifiers");
                });

            modelBuilder.Entity("MyTurn.Infrastructure.Data.Entities.PlayerEntity", b =>
                {
                    b.Navigation("Equipment");

                    b.Navigation("InventoryStacks");

                    b.Navigation("Skills");

                    b.Navigation("Stats");
                });

            modelBuilder.Entity("MyTurn.Infrastructure.Data.Entities.SaveSlotEntity", b =>
                {
                    b.Navigation("Player");

                    b.Navigation("WorldSessions");
                });

            modelBuilder.Entity("MyTurn.Infrastructure.Data.Entities.WorldSessionEntity", b =>
                {
                    b.Navigation("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
